Shared state task
yuliyahrudzko/playwright-page-object pull request #1
Opened 2024-04-18 11:19 UTC by yuliyahrudzko

2024-04-18 11:46 UTC, avient requested changes

2024-04-18 11:46 UTC, avient commented on tests/test.spec.js
Зачем нужен файл tests/test.spec.js ?

2024-04-18 11:46 UTC, avient commented on tests/test.spec.ts
> +  let n, token, userID, booksResponse, listOfAllBooks, booksInUserProfile, secondBookInProfile, listOfUserBooks;
Старайся избегать коротких/однобуквенных переменных

2024-04-18 11:46 UTC, avient commented on utils/api-party.ts
> +          'collectionOfIsbns': [
С учетом того, что тут принимается массив, лучше сделать всё одним запросом, а не циклом

2024-04-18 11:46 UTC, avient commented on tests/test.spec.ts
> +    booksInUserProfile = await apiParty.addBookToUserProfile(userID, token, n, listOfAllBooks);
Книги нужно выбрать случайно, а не первые `n`

2024-04-18 11:46 UTC, avient commented on tests/test.spec.ts
> +  await test.step('Check number of books in user profile', async () => {
Проверку выполнить через UI

2024-04-18 11:46 UTC, avient commented on tests/test.spec.ts
> +  await test.step('Check that information for added books is correct', async () => {
Проверки выполнить через UI

2024-04-18 11:46 UTC, avient commented on tests/test.spec.ts
> +    await profile.clickDeleteIcon();
Тут точно удаляется вторая по списку книга?

2024-04-18 11:46 UTC, avient commented on tests/test.spec.ts
> +    expect(page.locator('#closeSmallModal-cancel')).toHaveText('Cancel');
Что такое Page Object?

Пропущены await при работе с локаторами

2024-04-18 11:46 UTC, avient commented on tests/test.spec.ts
> +  await test.step('Verify book was deleted', async () => {
Выполнить через UI

2024-04-18 11:46 UTC, avient commented on tests/test.spec.ts
> +    expect(page.locator('#closeSmallModal-cancel')).toHaveText('Cancel');
Что такое Page Object?

Пропущены await при работе с локаторами

2024-04-18 11:46 UTC, avient commented on tests/test.spec.ts
> +  await test.step('Verify all books were deleted', async () => {
Выполнить через UI

2024-04-18 11:47 UTC, avient commented
Тест падает если в профиле уже есть добавленные книги

2024-04-19 13:29 UTC, yuliyahrudzko commented on tests/test.spec.js
Deleted ✔

2024-04-19 13:29 UTC, yuliyahrudzko commented on tests/test.spec.ts
> +  let n, token, userID, booksResponse, listOfAllBooks, booksInUserProfile, secondBookInProfile, listOfUserBooks;
Changed ✔

2024-04-19 13:29 UTC, yuliyahrudzko commented on utils/api-party.ts
> +          'collectionOfIsbns': [
Не совсем понимаю, что ты имеешь ввиду ❓

2024-04-19 13:30 UTC, yuliyahrudzko commented on tests/test.spec.ts
> +    booksInUserProfile = await apiParty.addBookToUserProfile(userID, token, n, listOfAllBooks);
Done ✔

2024-04-19 13:30 UTC, yuliyahrudzko commented on tests/test.spec.ts
> +  await test.step('Check number of books in user profile', async () => {
Done ✔

2024-04-19 13:30 UTC, yuliyahrudzko commented on tests/test.spec.ts
> +    await profile.clickDeleteIcon();
Yes 👀

2024-04-19 13:30 UTC, yuliyahrudzko commented on tests/test.spec.ts
> +    expect(page.locator('#closeSmallModal-cancel')).toHaveText('Cancel');
Done ✔

2024-04-19 13:30 UTC, yuliyahrudzko commented on tests/test.spec.ts
> +  await test.step('Verify book was deleted', async () => {
Done ✔

2024-04-19 13:30 UTC, yuliyahrudzko commented on tests/test.spec.ts
> +    expect(page.locator('#closeSmallModal-cancel')).toHaveText('Cancel');
Done ✔

2024-04-19 13:30 UTC, yuliyahrudzko commented on tests/test.spec.ts
> +  await test.step('Verify all books were deleted', async () => {
Done ✔

2024-04-19 13:33 UTC, yuliyahrudzko commented
> Тест падает если в профиле уже есть добавленные книги
Нужно добавить дополнительную проверку?

2024-05-23 12:24 UTC, avient requested changes

2024-05-23 12:24 UTC, avient commented on tests/test.spec.ts
> +test.only('Task 7: Shared State', async ({ page }) => {
.only

2024-05-23 12:24 UTC, avient commented on package.json
> +    "chance": "^1.1.11",
В чем разница "devDependencies" и "dependencies" ?

2024-05-23 12:24 UTC, avient commented on utils/api-party.ts
> +      return obj;
можно вернуть сразу, без объявления переменной

2024-05-23 12:44 UTC, yuliyahrudzko commented on package.json
> +    "chance": "^1.1.11",
**Dependencies:**

1. Dependencies are the packages that your project **directly depends on to run** in production.
2. These packages **are necessary for your application to work** as intended when it’s deployed or used by end-users.
3. These dependencies are typically things like web frameworks, utility libraries, or other modules that your code relies on.


**DevDependencies**

1. DevDependencies are packages that are only needed **for development and testing purposes**.
2. These packages **are not required** for your application to function in production, so they are not included when your project is deployed.
3. Examples of devDependencies are testing libraries, build tools, code linters, and other development-related utilities.

2024-05-23 13:11 UTC, avient commented on package.json
> +    "chance": "^1.1.11",
ок, что-нибудь менять у себя будешь?

2024-05-23 13:25 UTC, yuliyahrudzko commented on package.json
> +    "chance": "^1.1.11",
нет)

2024-05-23 15:37 UTC, avient commented on package.json
> +    "chance": "^1.1.11",
В тестовом фрейме обычно всё идёт в devDependencies

2024-05-24 12:55 UTC, yuliyahrudzko commented on package.json
> +    "chance": "^1.1.11",
@avient получается всё с Dependencies перенести в devDependencies?

2024-05-27 07:14 UTC, avient commented on package.json
> +    "chance": "^1.1.11",
да

2024-05-27 08:31 UTC, yuliyahrudzko commented on package.json
> +    "chance": "^1.1.11",
updated @avient

2024-05-27 12:24 UTC, avient approved these changes

2024-05-27 12:53 UTC, merged